default: &default
  adapter: postgresql
  pool: 10
  timeout: 5000
  username: cosmosloth
  password: real2010

development:
  <<: *default
  database: spree_store_development

test:
  <<: *default
  database: spree_store_test
